// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// author: SketchSupreme (https://sketchfab.com/ispeakzhongwen22)
// license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// source: https://sketchfab.com/3d-models/mandalorian-the-fortnite-season-6-skin-updated-92cc2754e8d649b4846047175f234566
// title: Mandalorian | The Fortnite Season 6 Skin UPDATED
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Model(props) {
  
//   const group = useRef()
//   const { nodes, materials } = useGLTF('/scene.gltf')

//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         <group rotation={[Math.PI / 2, 0, 0]}>
//           <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
//             <primitive object={nodes._rootJoint} />
//             <skinnedMesh
//               geometry={nodes.M_MED_Cosmosmo001_M_MED_Cosmos_Body_0.geometry}
//               material={nodes.M_MED_Cosmosmo001_M_MED_Cosmos_Body_0.material}
//               skeleton={nodes.M_MED_Cosmosmo001_M_MED_Cosmos_Body_0.skeleton}
//             />
//             <skinnedMesh
//               geometry={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Armor_0.geometry}
//               material={materials.M_MED_Cosmos_Armor}
//               skeleton={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Armor_0.skeleton}
//             />
//             <skinnedMesh
//               geometry={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Body_0.geometry}
//               material={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Body_0.material}
//               skeleton={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Body_0.skeleton}
//             />
//             <skinnedMesh
//               geometry={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Head_0.geometry}
//               material={materials.M_MED_Cosmos_Head}
//               skeleton={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Head_0.skeleton}
//             />
//             <skinnedMesh
//               geometry={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Cape_0.geometry}
//               material={materials.M_MED_Cosmos_Cape}
//               skeleton={nodes.M_MED_Cosmosmo_M_MED_Cosmos_Cape_0.skeleton}
//             />
//             <skinnedMesh
//               geometry={nodes.SK_Pickaxe_Cosmos_Weaponmo_MI_Rifle_Cosmo_0.geometry}
//               material={materials.MI_Rifle_Cosmo}
//               skeleton={nodes.SK_Pickaxe_Cosmos_Weaponmo_MI_Rifle_Cosmo_0.skeleton}
//             />
//           </group>
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/scene.gltf')
