import * as THREE from "three";
import React, { useRef, useEffect, useMemo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

/* Auto-generated by https://github.com/pmndrs/gltfjsx */

const normalMaterial = new THREE.MeshNormalMaterial();

export function Fragments({ visible, ...props }) {
  console.log("fragment")
  const group = useRef();
  const { scene, animations, materials } = useGLTF("/hello-fragments.glb");
  const { actions } = useAnimations(animations, group);
  useMemo(
    () =>
      scene.traverse(
        (o) =>
          o.type === "Mesh" &&
          o.material === materials.inner &&
          (o.material = normalMaterial)
      ),
    [scene, materials.inner]
  );
  useEffect(() => {
    if (visible)
      Object.keys(actions).forEach((key) => {
        actions[key].repetitions = 0;
        actions[key].clampWhenFinished = true;
        actions[key].play();
      });
  }, [visible, actions]);
  return <primitive ref={group} object={scene} {...props} />;
}

export function Model(props) {
  console.log("tecxttttt")
  const { scene } = useGLTF("/hello-text.glb");
  return <primitive object={scene} {...props} />;
}

useGLTF.preload("/hello-text.glb");
useGLTF.preload("/hello-fragments.glb");
